name: Greeting on variable day

on:
  workflow_dispatch:
   inputs:
    username:
     description: "eneter your name"
     required: true
     default: "guset"


jobs:
  create-user:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: "Step 1"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: sandeep
          DAY_OF_WEEK: sunday
          Greeting: Hello
      - name: print usename
        run: echo "${{github.event.inputs.username}}" >> $GITHUB_OUTPUT
        
  show-user:
     needs: create-user
     runs-on: ubuntu-latest
     steps: 
      - name: show username
        run: echo "the usename is ${{needs.create-user.outputs.GITHUB_OUTPUT}}
       
