name: con-job 
on: 
 push:
  branches:
  - main


jobs:
  get-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        uses: actions/checkout@v3
      - name: print message
        run: |
         echo "hello sandeep"   
         sleep 20
         echo "this is final message"
         
         
      

    
