name: Execution flow
on:
  push:
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: build job
     run: echo "building the application"
     run: touc file.txt
     
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: test job
     run: echo "testing  the application"
     
  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
   - name: deploy job
     run: echo "deploy the application"
