
name: Inputs and Outputs Lab

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your name"
        required: true
        default: "Guest"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Save Greeting
        id: step1
        run: echo "greet_msg=Hello ${{ github.event.inputs.username }}" >> $GITHUB_OUTPUT

      - name: Use Greeting
        run: echo "Final message is ${{ steps.step1.outputs.greet_msg }}"


